error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:20:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> tests/ui/same_name_method.rs:26:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   = note: `-D clippy::same-name-method` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::same_name_method)]`

error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:36:13
   |
LL |             fn clone() {}
   |             ^^^^^^^^^^^^^
   |
note: existing `clone` defined here
  --> tests/ui/same_name_method.rs:32:18
   |
LL |         #[derive(Clone)]
   |                  ^^^^^
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:48:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> tests/ui/same_name_method.rs:54:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^

error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:64:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> tests/ui/same_name_method.rs:69:9
   |
LL |         impl T1 for S {}
   |         ^^^^^^^^^^^^^^^^

error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:78:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> tests/ui/same_name_method.rs:85:9
   |
LL |         impl T1 for S {}
   |         ^^^^^^^^^^^^^^^^

error: method's name is the same as an existing method in a trait
  --> tests/ui/same_name_method.rs:78:13
   |
LL |             fn foo() {}
   |             ^^^^^^^^^^^
   |
note: existing `foo` defined here
  --> tests/ui/same_name_method.rs:87:9
   |
LL |         impl T2 for S {}
   |         ^^^^^^^^^^^^^^^^

error: aborting due to 6 previous errors

